### ISSUE TITLE
usb 1-1.1: Incompatible EP setup for 0x81

### ISSUE THREAD

**Issue by andeledea** [Focusrite-Scarlett-on-Linux/sound-usb-kernel-module#14] opened 2022-05-05 18:06 UTC
I followed the steps in the README and after reboot dmesg says:
usb 1-1.1: Incompatible EP setup for 0x81 (for 20 times because I have a sarlett 18i8)

```
[ 1365.452880] usb 1-1.1: Incompatible EP setup for 0x81
[ 1365.452944] usb 1-1.1: Incompatible EP setup for 0x81
[ 1365.452989] usb 1-1.1: Incompatible EP setup for 0x81
[ 1365.453033] usb 1-1.1: Incompatible EP setup for 0x81
[ 1365.453076] usb 1-1.1: Incompatible EP setup for 0x81
[ 1365.453444] usb 1-1.1: Incompatible EP setup for 0x81
[ 1365.453495] usb 1-1.1: Incompatible EP setup for 0x81
[ 1365.453539] usb 1-1.1: Incompatible EP setup for 0x81
[ 1365.453583] usb 1-1.1: Incompatible EP setup for 0x81
[ 1365.453627] usb 1-1.1: Incompatible EP setup for 0x81
[ 1365.454086] usb 1-1.1: Incompatible EP setup for 0x81
[ 1365.454184] usb 1-1.1: Incompatible EP setup for 0x81
[ 1365.454270] usb 1-1.1: Incompatible EP setup for 0x81
[ 1365.454358] usb 1-1.1: Incompatible EP setup for 0x81
[ 1365.454443] usb 1-1.1: Incompatible EP setup for 0x81
[ 1365.455070] usb 1-1.1: Incompatible EP setup for 0x81
[ 1365.455199] usb 1-1.1: Incompatible EP setup for 0x81
[ 1365.455317] usb 1-1.1: Incompatible EP setup for 0x81
[ 1365.455433] usb 1-1.1: Incompatible EP setup for 0x81
[ 1365.455546] usb 1-1.1: Incompatible EP setup for 0x81

...

[ 1631.016624] usb 1-1.1: Product: Scarlett 18i8 USB
[ 1631.016628] usb 1-1.1: Manufacturer: Focusrite
[ 1631.016631] usb 1-1.1: SerialNumber: (serial number)
[ 1634.656791] usb 1-1.1: Focusrite Scarlett Gen 2/3 Mixer Driver enabled pid=0x8214

```

I found online this discussion on endevourOs: https://forum.endeavouros.com/t/solved-focusrite-saffire-6-usb-audio-input-causes-system-to-lock-up/23806

I'm running Ubuntu right now, maybe this is the problem? I was wondering if there was a solution similar to the one proposed on the forum but for Ubuntu since the problem is the same one.

**Comment by HinTak** [comment] 2022-05-06 00:13
The urls you referred to, suggested it is a hardware compatibility problem: the device, when connected to a USB 1.1 port, requires special drivers even on Mac/windows. Is your linux computer of really old hardware usb-wise?

**Comment by geoffreybennett** [comment] 2022-05-06 02:49
What kernel version are you using?

**Comment by andeledea** [comment] 2022-05-07 13:41
Thank you for the quick response!!
On my PC I have 3 USB ports + 1 USB C (I tried all 3 and they all give me the same error).
```
Bus 001 Device 002: ID 0438:7900 Advanced Micro Devices, Inc. Root Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 002: ID 04f2:b573  Electronics Co., Ltd HD WebCam
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

OS
Ubuntu 20.04.4 LTS x86_64
Kernel version
uname -r: 5.13.0-40-generic

Also, everytime i connected the Focusrite, my PC saw it as a MSD  (there is the icon in NAUTILUS). I found online that pressing the Phantom 48V (between channels 1-2) for 5 sec deactivates this mode, I tried but the icon was still there.
When I opened Alsamixer I saw only this 2 options:
![2022-05-07_12-14](https://user-images.githubusercontent.com/62064962/167249954-028da404-aac1-4046-be26-615d9ee1ece6.png)
I selected MSD and by pressing (M) I disabled MSD by software, now I can see in alsa mixer all the parameters of the device.

The errors in dmesg are still there
I want to add that, as soon as I connect the device this shows up in dmesg
```
Device= 6.10
[ 1873.011034] usb 2-2: New USB device strings: Mfr=1, Product=3, SerialNumber=2
[ 1873.011039] usb 2-2: Product: Scarlett 18i8 USB
[ 1873.011044] usb 2-2: Manufacturer: Focusrite
[ 1873.011047] usb 2-2: SerialNumber: nnnnn
[ 1876.668280] usb 2-2: Focusrite Scarlett Gen 2/3 Mixer Driver enabled pid=0x8214
```
as you can see the errors are not present at this moment,  they show up a few seconds later.
I tried the device with ardour using ALSA and it is working, I can record and route the channels (I haven't tried all functionalities yet), I'm having problems with ardour and jack, but that's another topic.

Summarizing: the errors are still there but at least it is working, still I'm trying to understand where the errors are coming from.

**Comment by geoffreybennett** [comment] 2022-05-08 15:17
For reference for anyone in the future trying to disable MSD mode using the 48V button: it needs to be held down while you power on the interface. Holding it down while the interface is on won't do anything.

I don't know if the "Incompatible EP setup" errors are meaningful, but Ubuntu 20.04 and kernel 5.13 are not the latest versions and developers are not going to want to try and debug issues that have probably already been fixed in current versions of the software.

I would suggest you try Ubuntu 22.04 for these other reasons too:
- you can use pipewire (it replaces pulseaudio and jack)
- instead of using alsamixer to route channels you can use https://github.com/geoffreybennett/alsa-scarlett-gui which is way easier to use

I'm going to close this issue because those errors are unlikely to be caused by the Scarlett mixer driver.

**Closed by geoffreybennett** 2022-05-08 15:17 UTC
